// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrvmflzbejnffjdrzaai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlydm1mbHpiZWpuZmZqZHJ6YWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjU0NjUsImV4cCI6MjA2NzA0MTQ2NX0.TTXaW-Rqe_GD_5UT_PlBBHm_Ti3teK9Gga_KP2S_BZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});